// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TGZG.战雷革命房间服务器;

#nullable disable

namespace 战雷革命房间列表服务器.Migrations.自由空域数据库_SQLiteMigrations
{
    [DbContext(typeof(自由空域数据库_SQLite))]
    partial class 自由空域数据库_SQLiteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TGZG.战雷革命房间服务器.玩家档案", b =>
                {
                    b.Property<int>("_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("击杀数")
                        .HasColumnType("INTEGER");

                    b.Property<int>("助攻数")
                        .HasColumnType("INTEGER");

                    b.Property<long>("子弹命中次数")
                        .HasColumnType("INTEGER");

                    b.Property<string>("密码")
                        .HasColumnType("TEXT");

                    b.Property<long>("射出子弹总数")
                        .HasColumnType("INTEGER");

                    b.Property<int>("死亡数")
                        .HasColumnType("INTEGER");

                    b.Property<long>("消息发送总数")
                        .HasColumnType("INTEGER");

                    b.Property<long>("爬高总高度")
                        .HasColumnType("INTEGER");

                    b.Property<long>("能量转化总量")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("语音总时长")
                        .HasColumnType("TEXT");

                    b.Property<string>("账号名")
                        .HasColumnType("TEXT");

                    b.HasKey("_");

                    b.ToTable("玩家档案");
                });
#pragma warning restore 612, 618
        }
    }
}
