// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TGZG.战雷革命房间服务器;

#nullable disable

namespace 战雷革命房间列表服务器.Migrations
{
    [DbContext(typeof(自由空域数据库_MySql))]
    partial class 自由空域数据库_MySqlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TGZG.战雷革命房间服务器.玩家档案", b =>
                {
                    b.Property<int>("_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("_"));

                    b.Property<int>("击杀数")
                        .HasColumnType("int");

                    b.Property<int>("助攻数")
                        .HasColumnType("int");

                    b.Property<long>("子弹命中次数")
                        .HasColumnType("bigint");

                    b.Property<string>("密码")
                        .HasColumnType("longtext");

                    b.Property<long>("射出子弹总数")
                        .HasColumnType("bigint");

                    b.Property<int>("死亡数")
                        .HasColumnType("int");

                    b.Property<long>("消息发送总数")
                        .HasColumnType("bigint");

                    b.Property<long>("爬高总高度")
                        .HasColumnType("bigint");

                    b.Property<long>("能量转化总量")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("语音总时长")
                        .HasColumnType("time(6)");

                    b.Property<string>("账号名")
                        .HasColumnType("longtext");

                    b.HasKey("_");

                    b.ToTable("玩家档案");
                });
#pragma warning restore 612, 618
        }
    }
}
